apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: instrument-management-service
  description: This service provides instrument and identity management features.
  tags:
    - dotnet
    - edgeos
spec:
  type: service
  lifecycle: production
  owner: yauth-club
